// Downloads the Google Fonts used by the theme catalog into worker/fonts/ and writes fonts.css.
// Run once when the theme catalog changes: node worker/scripts/fetch-fonts.mjs
// Fonts are bundled so renders never fetch them at render time (the worker runs without network).
import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const fontsDir = join(dirname(dirname(fileURLToPath(import.meta.url))), "fonts");

// family → weights. Single-weight display faces only ship 400.
const families = {
  "Archivo": [400, 700],
  "Archivo Black": [400],
  "Barlow": [400, 700],
  "Bebas Neue": [400],
  "Bodoni Moda": [400, 700],
  "DM Mono": [400],
  "EB Garamond": [400, 700],
  "Fredoka": [400, 700],
  "Hanken Grotesk": [400, 700],
  "IBM Plex Mono": [400],
  "Instrument Serif": [400],
  "Inter": [400, 700],
  "JetBrains Mono": [400],
  "Libre Baskerville": [400, 700],
  "Newsreader": [400, 700],
  "Playfair Display": [400, 700],
  "Quicksand": [400, 700],
  "Shrikhand": [400],
  "Source Serif 4": [400, 700],
  "Space Grotesk": [400, 700]
};

// A modern browser user agent makes Google Fonts return woff2.
const userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36";
const slug = (family) => family.toLowerCase().replace(/\s+/g, "-");

await rm(fontsDir, { recursive: true, force: true });
await mkdir(fontsDir, { recursive: true });
const faces = [];

for (const [family, weights] of Object.entries(families)) {
  const query = weights.length > 1 ? `${family.replace(/ /g, "+")}:wght@${weights.join(";")}` : family.replace(/ /g, "+");
  // Keep only the Latin subset of each weight. Google occasionally serves a non-woff2 variant, so retry.
  let blocks = [];
  for (let attempt = 1; attempt <= 3; attempt++) {
    const response = await fetch(`https://fonts.googleapis.com/css2?family=${query}&display=block`, { headers: { "user-agent": userAgent } });
    if (!response.ok) throw new Error(`${family}: Google Fonts returned ${response.status}`);
    const css = await response.text();
    blocks = [...css.matchAll(/\/\* latin \*\/\s*@font-face\s*{([^}]*)}/g)].map((match) => match[1]);
    if (blocks.length === weights.length && blocks.every((block) => /\.woff2\)/.test(block))) break;
    await new Promise((resolve) => setTimeout(resolve, 1000 * attempt));
  }
  if (blocks.length === 0) throw new Error(`${family}: no latin faces found`);
  for (const block of blocks) {
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? "400";
    const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
    if (!url) throw new Error(`${family} ${weight}: no woff2 url`);
    const file = `${slug(family)}-${weight}.woff2`;
    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
    await writeFile(join(fontsDir, file), bytes);
    faces.push(`@font-face { font-family: "${family}"; font-style: normal; font-weight: ${weight}; font-display: block; src: url("fonts/${file}") format("woff2");${range ? ` unicode-range: ${range};` : ""} }`);
    console.log(`${family} ${weight}: ${bytes.length} bytes`);
  }
}

await writeFile(join(fontsDir, "fonts.css"), `/* Generated by worker/scripts/fetch-fonts.mjs from Google Fonts (SIL Open Font License). Do not edit. */\n${faces.join("\n")}\n`);
await writeFile(join(fontsDir, "LICENSE.md"), "All fonts in this directory are from Google Fonts and licensed under the SIL Open Font License 1.1 (https://openfontlicense.org). Each family's copyright and license text: https://fonts.google.com/specimen/<Family+Name>/license\n");
console.log(`${faces.length} faces written to ${fontsDir}`);
