import Link from "next/link";
import { PublicPage } from "../../components/public-page";
import { publicPageMetadata } from "../../lib/public-policies";

export const metadata = publicPageMetadata("Privacy", "How Greedy Motion processes account information, uploaded media and project data.");
export default function PrivacyPage() {
  return <PublicPage title="Privacy notice" description="How information is used to provide the website and video creation service.">
    <section><h2>Information involved in the service</h2><p>Account information includes your name, email address, authentication identifiers and session information. When you use Google sign-in, the authentication provider receives the profile information you authorize. Password authentication is handled by our authentication provider.</p><p>Project information includes briefs, scripts, screenshots, brand assets, uploaded fonts, website URLs and extracted website content, editing choices, review comments, generated audio and rendered videos. Support correspondence includes information you choose to send us. Hosting and application services also process technical request information, such as IP addresses, request times, error messages and device or browser information.</p></section>
    <section><h2>Why information is processed</h2><p>We use information to authenticate users, save and retrieve projects, plan and render videos, deliver results, respond to support requests, investigate errors, prevent misuse and meet applicable obligations. Only submit material you have the right to use and share for these purposes. Remove personal, confidential or sensitive information from screenshots and briefs when it is not needed for the video.</p></section>
    <section><h2>AI processing</h2><p>AI features send relevant inputs to model providers to fulfil your request. These can include briefs, script text, brand descriptions, screenshot names and purposes, and extracted website text. Anthropic supports story planning; Google supports configured voice and music generation features. The selected feature determines which provider receives information. Generated results are saved with the project where supported.</p><p>Provider retention and processing practices are governed by the applicable provider terms and configuration. Do not assume that information sent to an AI feature stays exclusively within Greedy Motion. Review generated content before using it.</p></section>
    <section><h2>Service providers and storage</h2><p>The service uses Vercel for the website, Railway for backend hosting, AWS for video rendering, Supabase for authentication and PostgreSQL data, Cloudflare R2 for rendered output storage, and Resend for authentication email delivery. Project media may also be stored on the backend's persistent disk. Providers may process information in countries other than yours.</p><p>We may disclose relevant information when required by law, to protect users or the service, or as part of a business transfer subject to applicable obligations. A separate billing disclosure will be provided before paid checkout is enabled; a proposed payment integration does not mean payments are currently available.</p></section>
    <section><h2>Cookies and session storage</h2><p>Authentication uses session cookies to keep you signed in and refresh your session. The editor also uses browser state for editing and undo history. Blocking necessary cookies may prevent sign-in from working. Additional optional tracking should be described here before it is introduced.</p></section>
    <section><h2>Media links and sharing</h2><p>Some preview, screenshot and rendered-video URLs can be accessed by anyone who possesses the link. Treat these links as private and do not share them unless you intend to give access to the media. Account sign-in does not make every media link access-controlled.</p></section>
    <section><h2>Retention and requests</h2><p>Saved projects persist across sessions; signing out does not delete them. Some data may remain in provider backups or operational logs after removal from the active service. Retention needs include providing saved projects, resolving support issues, preventing abuse and meeting legal obligations.</p><p>You can request access, correction, an export or deletion through the <Link href="/contact">contact page</Link>. We may verify the requester and explain any information that must be retained. Rights and response requirements depend on applicable law; where available, you may also complain to your relevant privacy regulator.</p></section>
    <section><h2>Updates and questions</h2><p>We will revise this notice when the service or its data practices change. Material changes should be communicated as required by applicable law. Contact us with questions before uploading information you are unsure about sharing.</p></section>
  </PublicPage>;
}
