import Link from "next/link";
import { PublicPage } from "../../components/public-page";
import { businessProfile } from "../../lib/business-profile";
import { publicPageMetadata } from "../../lib/public-policies";

export const metadata = publicPageMetadata("Terms", "Terms for using Greedy Motion's video creation software.");
export default function TermsPage() {
  return <PublicPage title="Terms of service" description="The responsibilities that apply when using Greedy Motion.">
    <section><h2>The service and your account</h2><p>Greedy Motion provides online software for planning, editing, reviewing and rendering product videos. You must have legal capacity to enter into these terms and authority to use the service on behalf of any organization you represent. Provide accurate account information, keep your credentials secure and report suspected unauthorized access through our <Link href="/contact">contact page</Link>.</p></section>
    <section><h2>Your content and permissions</h2><p>You retain any rights you hold in the material you upload. You authorize us and our service providers to store, process, reproduce and transform that material as necessary to provide the requested service, generate outputs and address support or security issues.</p><p>You must have permission to use uploaded screenshots, trademarks, fonts, music, images and other content, including any personal information they contain. Do not submit illegal content, malware, stolen credentials, material that infringes others' rights, or deceptive impersonations. Do not bypass access controls, probe other users' projects or overload the service.</p></section>
    <section><h2>Generated output</h2><p>AI-generated text, audio and video may be inaccurate, non-unique or unsuitable for your intended use. Review output for accuracy, rights, consent and brand suitability before publishing. Your rights to an output depend on your input rights, applicable law and any third-party asset or provider terms. We do not promise exclusive copyright or clearance of third-party rights.</p><p>Greedy Motion's software, interface and supplied templates remain subject to their respective intellectual property rights. Access to the editor does not transfer ownership of the software or authorize resale of its templates as standalone products.</p></section>
    <section><h2>Charges and subscriptions</h2><p>{businessProfile.billingDescription ?? "Billing arrangements, prices, usage limits and any trial conditions require owner confirmation before paid access is offered. No paid checkout is provided by this draft."}</p><p>Any paid offer must identify the amount, currency, billing interval, applicable taxes, included usage and renewal terms before you accept a charge. See the <Link href="/refunds">refund and cancellation policy</Link> for the applicable rules. Creating an account alone does not authorize a future charge.</p></section>
    <section><h2>Availability and delivery</h2><p>Outputs are supplied digitally through your project. Generation time depends on project complexity, available rendering capacity and external services. Features, file compatibility and availability may change; retain your own copies of source materials and downloaded outputs. We cannot guarantee uninterrupted operation or that every generation will succeed.</p></section>
    <section><h2>Suspension and account closure</h2><p>We may restrict access where reasonably necessary to address misuse, security threats, legal requirements or breaches of these terms. Contact support to request account closure or challenge an access restriction. Account closure, cancellation of a paid subscription and deletion of personal information are separate requests; specify which you need.</p></section>
    <section><h2>Service limitations</h2><p>To the extent permitted by applicable law, the service and AI outputs are provided as available, without warranties of uninterrupted availability, error-free output, fitness for a particular purpose or non-infringement. We do not guarantee sales, engagement, commercial results or any particular generation time. These limitations do not remove any express commitment made at purchase or mandatory standards for digital services.</p></section>
    <section><h2>Limitation of liability</h2><p>To the extent permitted by applicable law, neither Ramolabs nor its service providers will be liable under these terms for indirect or consequential losses, or lost profits, revenue, business opportunities or anticipated savings. Ramolabs' aggregate liability arising from the service is limited to the fees you paid for Greedy Motion during the 12 months preceding the event giving rise to the claim.</p><p>These exclusions and cap do not apply to fraud, fraudulent misrepresentation, wilful misconduct, death or personal injury caused by negligence, or any liability that applicable law does not allow us to exclude or limit. They do not limit mandatory consumer remedies or refunds due under our refund policy.</p></section>
    <section><h2>Third-party claims involving business customers</h2><p>If you use the service on behalf of a business, to the extent permitted by law you agree to indemnify Ramolabs for reasonable costs and damages from third-party claims caused by your unlawful uploads, infringement of third-party rights in your supplied material, or deliberate misuse of the service. This does not cover claims caused by our own breach, negligence or misconduct. We will promptly notify you, reasonably cooperate and allow you to control the defence with suitable counsel; no settlement may impose an admission or obligation on us without our consent, which will not be unreasonably withheld. This provision does not apply to consumers acting outside their trade or profession.</p></section>
    <section><h2>Privacy and applicable rights</h2><p>The <Link href="/privacy">privacy notice</Link> describes processing of account and project information. Nothing in these terms excludes rights or remedies that cannot lawfully be excluded. Applicable mandatory consumer rights take priority over conflicting terms.</p></section>
    <section><h2>Changes and contact</h2><p>Changes to these terms will be published here and communicated where required. Material changes to paid offers should be disclosed before they take effect. Questions or complaints can be sent through the <Link href="/contact">contact page</Link>.</p></section>
  </PublicPage>;
}
